### ISSUE TITLE
Setting a keg weight or volume to 0 causes a division by zero error

### ISSUE THREAD

**Issue by yesrod** [yesrod/hoplite#2]
This happens in both web and main processes.

```
Apr 26 21:18:37 hoplite python2[2293]:   File "build/bdist.linux-armv6l/egg/hoplite/__main__.py", lin
Apr 26 21:18:37 hoplite python2[2293]:   File "build/bdist.linux-armv6l/egg/hoplite/__main__.py", lin
Apr 26 21:18:37 hoplite python2[2293]:   File "build/bdist.linux-armv6l/egg/hoplite/hoplite.py", line
Apr 26 21:18:37 hoplite python2[2293]:   File "build/bdist.linux-armv6l/egg/hoplite/hoplite.py", line
Apr 26 21:18:37 hoplite python2[2293]:   File "build/bdist.linux-armv6l/egg/hoplite/hoplite.py", line
Apr 26 21:18:37 hoplite python2[2293]:   File "build/bdist.linux-armv6l/egg/hoplite/hoplite.py", line
Apr 26 21:18:37 hoplite python2[2293]: ZeroDivisionError: float division by zero
Apr 26 21:18:37 hoplite python2[2294]: remi.update      ERROR    error updating gui
Apr 26 21:18:37 hoplite python2[2294]: Traceback (most recent call last):
Apr 26 21:18:37 hoplite python2[2294]:   File "/usr/local/lib/python2.7/dist-packages/remi/server.py"
Apr 26 21:18:37 hoplite python2[2294]:     client.idle()
Apr 26 21:18:37 hoplite python2[2294]:   File "build/bdist.linux-armv6l/egg/hoplite/web.py", line 95,
Apr 26 21:18:37 hoplite python2[2294]:     i = int(index) - 1
Apr 26 21:18:37 hoplite python2[2294]:   File "build/bdist.linux-armv6l/egg/hoplite/web.py", line 77,
Apr 26 21:18:37 hoplite python2[2294]:     except KeyError:
Apr 26 21:18:37 hoplite python2[2294]: ZeroDivisionError: float division by zero
```

**Comment by yesrod** [comment]
This happens when any of the size parameters in the config are set to zero.

Need to implement some method of checking and correcting those when a config is loaded or passed back from the web process via shmem.

**Comment by yesrod** [comment]
This will be fixed as part of implementing the REST API, as that will become the one supported method for configuring Hoplite.
